# Generated by Django 4.0.1 on 2022-01-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='email',
        ),
    ]
